# Site settings
title: Yammong
email: emaehol28@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Yeongjin Kim Personal Blog

baseurl: ""
url: "https://yammong.github.io"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
